name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache npm modules
        uses: actions/cache@v3
        with:
          path: gift-wishlist/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('gift-wishlist/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        working-directory: gift-wishlist
        run: npm install

      - name: Run Tests
        working-directory: gift-wishlist
        run: npm test

      - name: Build
        working-directory: gift-wishlist
        run: npm run build
        env:
          CI: false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gift-wishlist/build
